<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => '列',
    'Comma Separated Values' => '以逗号分割的值',
    'Upload imported file' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Import data' => '导入数据',
    'Import Zip File for imgs' => '上传图片文件夹压缩Zip',
    'Import data in selected format' => '以选定格式导入数据',
    'Imported File' => '',
    'Importing the file. Please wait...' => '正在导入文件，请稍后...',
    'Grid import generated by Krajee ImportMenu widget (yii2-import)' => '表格数据由Krajee的ImportMenu组件(yii2-import)生成导入',
    'HTML' => '',
    'Hyper Text Markup Language' => '超文本标记语言',
    'Microsoft Excel 2007+ (xlsx)' => '微软Excel版本07以上',
    'Microsoft Excel 95+ (xls)' => '微软Excel版本95以上',
    'Ok to proceed?' => '确定继续?',
    'PDF' => '',
    'Portable Document Format' => '便携的文档格式',
    'Request submitted! You may safely close this dialog after saving your uploaded file.' => '请求已提交!你可以在下载完文件后安全地关闭本对话框。',
    'Select Columns' => '选择列',
    'Select columns to import' => '选择导入列',
    'Tab Delimited Text' => 'Tab分隔的文本',
    'Text' => '文本',
    'The CSV import file will be generated for upload.' => 'CSV文件即将生成下载。',
    'The EXCEL 2007+ (xlsx) import file will be generated for upload.' => 'EXCEL 2007+ (xlsx)文件即将生成下载。',
    'The EXCEL 95+ (xls) import file will be generated for upload.' => 'EXCEL 95+ (xls)文件即将生成下载。',
    'The HTML import file will be generated for upload.' => 'HTML文件即将生成下载。',
    'The PDF import file will be generated for upload.' => 'PDF文件即将生成下载。',
    'The TEXT import file will be generated for upload.' => 'TEXT文件即将生成下载。',
    'grid-import' => '表格导入',
    'Toggle All' => '反选所有',
];

