<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CSV' => '',
    'Column' => '',
    'Comma Separated Values' => '',
    'Upload imported file' => '',
    'Excel 2007+' => '',
    'Excel 95 +' => '',
    'Import data' => '',
    'Import Zip File for imgs' => '',
    'Import data in selected format' => '',
    'Imported File' => '',
    'Importing the file. Please wait...' => '',
    'Grid import generated by Krajee ImportMenu widget (yii2-import)' => '',
    'HTML' => '',
    'Hyper Text Markup Language' => '',
    'Microsoft Excel 2007+ (xlsx)' => '',
    'Microsoft Excel 95+ (xls)' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your uploaded file.' => '',
    'Select Columns' => '',
    'Select columns to import' => '',
    'Tab Delimited Text' => '',
    'Text' => '',
    'The CSV import file will be generated for upload.' => '',
    'The EXCEL 2007+ (xlsx) import file will be generated for upload.' => '',
    'The EXCEL 95+ (xls) import file will be generated for upload.' => '',
    'The HTML import file will be generated for upload.' => '',
    'The PDF import file will be generated for upload.' => '',
    'The TEXT import file will be generated for upload.' => '',
    'grid-import' => '',
    'Toggle All' => '',
];
